# Generated by Django 3.1.1 on 2020-12-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesslisting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='Contact',
            new_name='contact',
        ),
    ]
